LightGCN:
  params:
    n_layers: 3
    embedding_dim: 128
    batch_size: 2048
    n_epochs: 30
    patience: 5
    learning_rate: 0.00001
  split:
    test_size: 0.2
    random_state: 42
  preprocessed: True
  data_split: False
  top_k: 10

dataset :
  data_path : ../train/
  output_path : saved/output
  preprocessing_path : saved/preprocessed/