seed : 0
device: cpu
model: FM

model_args:
  EASE:
    _lambda : 1000
  SASRec:
    Create : False

EASER:
  create: True
  epochs: 1
  threshold: 3500
  lambdaBB: 1000
  lambdaCC: 10000
  rho: 50000
  k: 10

RecVAE:
  create: True
  hidden_dim: 600
  latent_dim: 200
  batch_size: 500
  beta: None
  gamma: 0.003
  lr: 0.0005
  n_epochs: 1
  n_enc_epochs: 3
  n_dec_epochs: 1
  not_alternating: False

  threshold: None
  min_users_per_item: 1
  min_items_per_user: 0

FM:
    seed: 0
    batch_size: 4096
    epochs: 1
    embed_dim: 1
    learning_rate: 0.01
    weight_decay: 1e-4
    valid_ratio: 0.1
    shuffle: True


dataset :
  data_path : ../train/
  output_path : saved/output
  preprocessing_path : saved/preprocessed/