seed : 0
device: cpu
model: NCF

model_args:
  NCF:
    embed_dim: 16
    hidden_dim: 64

    epochs: 10
    lr: 0.001
    batch_size: 64
    num_negatives: 4

    top_k: 10

  
dataset:
  data_path : ../train/
  output_path: "output/NCF.csv"
