seed : 0
device: cpu
model: SASRec



model_args:
  SASRec:
    item_attribute_create : True

    data_name : M1
    model_name : Finetune_full
    using_pretrain : store_true
    create_pretrain: False

    seed : 42
    gpu_id : '0'
    no_cuda : store_true

    log_freq : 1

    pre_epochs: 300
    pre_batch_size: 512
    maks_p: 0.2
    aap_weight: 0.2
    mip_weight: 1.0
    map_weight: 1.0
    sp_weight: 1.0

    hidden-size : 256
    num_hidden_layers : 2
    num_attention_heads : 2
    hidden-act : gelu
    attention_probs_dropout_prob : 0.3
    hidden-dropout_prob : 0.5
    initializer_range : 0.02
    max_seq_length : 50
    weight_decay : 0.02
    adam_beta1 : 0.9
    adam_beta2 : 0.999

    lr : 0.0001
    batch_size : 256
    epochs : 200





dataset :
  data_path : ../train/
  output_path : saved/output
  preprocessing_path : saved/preprocessed/